version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore:"
    labels:
      - "type: maintanance"
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    labels:
      - "type: maintanance"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "globals"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore:"
    labels:
      - "type: maintanance"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"] # Use the latest LTS version
